server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dspm
    username: dspm
    password: dspm
    driver-class-name: org.postgresql.Driver

  jpa:
    # 개발 편의용: 엔티티 변경 시 테이블 자동 반영
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info   # 바인딩 값 로깅 (필요 없으면 낮추기)
